sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tQKHwc5DxawATxtTozY
    accessKeySecret: gZfn8zwf4GmHXeX57MxLCLEZoSxIYK
    bucketName: web-tlias0917
  redis:
    host: localhost
    port: 6379
    password:
  wechat:
    appid: wxda8744f3dedb071a
    secret: a8257fefb632568900b4741eaf679fa1
